export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const RESET_MARKY_FILE = 'RESET_MARKY_FILE';


export const HAVE_FOLDER = 'HAVE_FOLDER';
export const HAVE_FILE = 'HAVE_FILE';

export const SETUP_BOOKMARKS = 'SETUP_BOOKMARKS';

export const OPEN_CATEGORY = 'OPEN_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const INPUTTING_BOOKMARK_NAME = 'INPUTTING_BOOKMARK_NAME';
export const INPUTTING_BOOKMARK_URL = 'INPUTTING_BOOKMARK_URL';
export const INPUTTING_CATEGORY_NAME = 'INPUTTING_CATEGORY_NAME';


export const ADD_BOOKMARK_TO_STATE = 'ADD_BOOKMARK_TO_STATE';
export const REMOVE_BOOKMARK_FROM_STATE = 'REMOVE_BOOKMARK_FROM_STATE';
export const ADD_CATEGORY_TO_STATE = 'ADD_CATEGORY_TO_STATE';
